open_assetmanagement/inventory/urls.py
from django.urls import path

from . import views

app_name = 'inventory'
urlpatterns = [
    path('table/', views.index, name='index'),
    path('', views.dashboard, name='dashboard'),

    # User Management
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout"),

    # Excel/CSV Download and Upload
    path('upload/', views.upload_file, name='upload_file'),
    path('download/', views.download_file, name='download'),

    # Import Modules
    path('networkscan/', views.network_scan, name='netscan'),
    path('s7scan/', views.s7_scan, name='s7scan'),

    # Object CRUD
    path('device/<int:pk>', views.device, name='device'),
    path('device/<int:pk>/change/', views.change_device, name='change_device'),
    path('device/<int:pk>/delete/', views.delete_device, name='delete_device'),
    path('device/create/', views.create_device, name='create_device'),

    path('product/<int:pk>', views.product, name='product'),
    path('product/<int:pk>/delete/', views.delete_product, name='delete_product'),
    path('product/<int:pk>/change/', views.change_product, name='change_product'),
    path('product/create/', views.create_product, name='create_product'),

    path('supplier/<int:pk>', views.supplier, name='supplier'),
    path('supplier/<int:pk>/delete/', views.delete_supplier, name='delete_supplier'),
    path('supplier/<int:pk>/change/', views.change_supplier, name='change_supplier'),
    path('supplier/create/', views.create_supplier, name='create_supplier'),

    path('software/<int:pk>', views.software, name='software'),
    path('software/<int:pk>/delete/', views.delete_software, name='delete_software'),
    path('software/<int:pk>/change/', views.change_software, name='change_software'),
    path('software/create/', views.create_software, name='create_software'),
]

open_assetmanagement/open_assetmanagement/urls.py
"""
open_assetmanagement URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:

Function view
1. Add an import:  from my_app import views
2. Add a URL to urlpatterns:  path('', views.home, name='home')

Class-based views
1. Add an import:  from other_app.views import Home
2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')

Including another URLconf
1. Import the include() function: from django.urls import include, path
2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

"""

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls')),
]

open_assetmanagement/inventory/forms.py
import magic
from django import forms
from .models import Device, Product, ProductSupplier, Software
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        exclude = []


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


class SupplierForm(forms.ModelForm):
    class Meta:
        model = ProductSupplier
        exclude = []


class SoftwareForm(forms.ModelForm):
    class Meta:
        model = Software
        exclude = []


class NetworkdiscoveryForm(forms.Form):
    ip_range = forms.CharField()
    type = forms.ChoiceField(
        choices=[
            (0, 'Very Careful - Only passive Arp Scan (Netdiscover)'),
            (1, 'Careful - Only active Arp Scan (Netdiscover)'),
            (2, "Medium - NMAP TCP-SYN Scan"),
            (3, "Os - NMAP OS Scan and CME Scan"),
            (4, "Full - Full Port Scan"),
        ]
    )
    timeout = forms.ChoiceField(
        choices=[
            (15, 'Very Fast - 15 Seconds'),
            (60, 'Fast - 1 Minute'),
            (300, "Medium - 5 Minutes"),
            (3600, "Slow - 1 Hour"),
        ]
    )


class S7discoveryForm(forms.Form):
    ip_range = forms.CharField()


class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField()
    delimiter = forms.ChoiceField(
        choices=[
            (',', 'Unknown - Or Exel File'),
            (";", "Semicolon ';'"),
            (",", "Comma ','"),
        ]
    )

    def clean_title(self):
        data = self.cleaned_data['title']
        if "bad" in data:
            raise ValidationError(_('Invalid name'))

        # Remember to always return the cleaned data.
        return data

    def clean_file(self):
        file = self.cleaned_data.get("file", False)
        filetype = magic.from_buffer(file.read())
        if "text" not in filetype and "Microsoft Excel" not in filetype:
            raise ValidationError("Filetype ist wrong, you tried uploading: '" + filetype + "' but should have "
                                                                                            "uploaded: CSV or XLSX")
        return file

open_assetmanagement/inventory/views.py
from .models import Device, Product, ProductSupplier, Software
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from .forms import UploadFileForm, DeviceForm, ProductForm, SupplierForm, NetworkdiscoveryForm, CreateUserForm, \
    SoftwareForm, S7discoveryForm
from .filehandler import handle_uploaded_file, csv_to_device
from django.urls import reverse
from .tables import DeviceTable
from .filters import DeviceFilter
from django_tables2 import RequestConfig
from django_tables2.export.export import TableExport
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import csv
from .network_discovery_module import network_discovery, s7_discovery


@login_required(login_url='inventory:login')
def dashboard(request):
    """This is the view function for the Dashboard view (Home)
    It gets all the :class:`devices  <inventory.models.Device>`, :class:`products  <inventory.models.Product>`,
    :class:`suppliers  <inventory.models.ProductSupplier>` and :class:`software  <inventory.models.Software>` from the database
    It also creates the :class:`UploadFileForm  <inventory.forms.UploadFileForm>`, used for the Excel/CSV Import Functionality

    .. note::
        Only for logged in Users

    .. code-block::

        context = {
        'devices': devices,
        'products': products,
        'suppliers': suppliers,
        'softwares': softwares,
        'total_devices': devices.count(),
        'total_products': products.count(),
        'total_suppliers': suppliers.count(),
        'total_software': softwares.count(),
        'form': UploadFileForm(),
        }

    :param request:
    :return:
    """
    devices = Device.objects.all()
    products = Product.objects.all()
    suppliers = ProductSupplier.objects.all()
    softwares = Software.objects.all()
    context = {'devices': devices, 'products': products, 'suppliers': suppliers, 'softwares': softwares,
               'total_devices': devices.count(), 'total_products': products.count(),
               'total_suppliers': suppliers.count(), 'total_software': softwares.count(), 'form': UploadFileForm(),
               'networkdiscovery_form': NetworkdiscoveryForm(), 's7discovery_form': S7discoveryForm()}
    return render(request, "inventory/dashboard.html", context)


def register_page(request):
    """This is the view function for the registration
    It Uses the :class:`CreateUserForm  <inventory.forms.CreateUserForm>`

    :param request:
    :return:
    """
    if request.user.is_authenticated:
        return redirect('inventory:dashboard')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('inventory:login')

        context = {'form': form}
        return render(request, 'inventory/register.html', context)


def login_page(request):
    """This is the view function for the login

    :param request:
    :return:
    """
    if request.user.is_authenticated:
        return redirect('inventory:login')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('inventory:dashboard')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'inventory/login.html', context)


def logout_user(request):
    """This function logs the user out and redirects to the login page

    :param request:
    :return:
    """
    logout(request)
    return redirect('inventory:login')


@login_required(login_url='inventory:login')
def index(request):
    """This function provides the :class:`~inventory.tables.DeviceTable` for the table view. It also implements the
    export of the table view

    .. note::
        Only for logged in Users

    :param request:
    :return:
    """
    context = {}
    devices = Device.objects.all()
    context['table'] = DeviceTable(devices)
    return render(request, "inventory/index.html", context)


@login_required(login_url='inventory:login')
def upload_file(request):
    """This function implements the :class:`~inventory.forms.UploadFileForm`

    .. note::
        Only for logged in Users

    :param request:
    :return:
    """
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'], request.POST.get("delimiter"))
            return HttpResponseRedirect(reverse('inventory:dashboard'))
    else:
        form = UploadFileForm()
    return render(request, 'inventory/upload.html', {'form': form})


@login_required(login_url='inventory:login')
def network_scan(request):
    """This is the function to start a network_scan and hand the data to the filehandler

    .. note::
        Only for logged in Users

    :param request:
    :return:
    """
    csv_to_device(network_discovery(str(request.POST.get("ip_range")), int(request.POST.get("type")), int(request.POST.get("timeout"))))
    return HttpResponseRedirect(reverse('inventory:index'))


@login_required(login_url='inventory:login')
def s7_scan(request):
    """This is the function to start a s7_scan and hand the data to the filehandler

    .. note::
        Only for logged in Users

    :param request:
    :return:
    """
    csv_to_device(s7_discovery(str(request.POST.get("ip_range"))))
    return HttpResponseRedirect(reverse('inventory:index'))


@login_required(login_url='inventory:login')
def download_file(request):
    """This function lets the user download the whole database as csv

    .. note::
        Only for logged in Users

    :param request:
    :return:
    """
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="assets.csv"'},
    )
    writer = csv.writer(response)
    devices = Device.objects.all().values('id', 'device_name', 'product_id__product_supplier_id__name',
                                          'product_id__model', 'product_id__version', 'product_id__type',
                                          'product_id__endOfSupport', 'automatic_import', 'communication_capability',
                                          'criticality', 'csv_import', 'group', 'interdependencies', 'ip_address',
                                          'location', 'mac_address', 'network', 'os', 'product_id', 'redundancy',
                                          'role', 'serial_number', 'software', 'configuration_file')
    writer.writerow(devices.first().keys())
    for dev in devices:
        writer.writerow(dev.values())

    return response


@login_required(login_url='inventory:login')
def device(request, pk):
    """This is the function for the detail view for the :class:`~inventory.models.Device` model

    .. note::
        Only for logged in Users

    :param pk:
    :param request:
    :return:
    """
    device = Device.objects.get(pk=pk)
    softwares = device.software_set.all()
    context = {"pk": pk, "device": device, "softwares": softwares}
    return render(request, 'inventory/device.html', context)


@login_required(login_url='inventory:login')
def change_device(request, pk):
    """This is the function for the change view for the :class:`~inventory.models.Device` model
    It uses the :class:`~inventory.forms.DeviceForm`

    .. note::
        Only for logged in Users

    :param pk:
    :param request:
    :return:
    """
    device = Device.objects.get(pk=pk)
    if request.method == "POST":
        form = DeviceForm(request.POST, instance=device)
        if form.is_valid():
            form.save()
            messages.success(request, 'Changes successful!')
            return HttpResponseRedirect(reverse('inventory:dashboard'))
        else:
            messages.error(request, 'Error saving form')
    form = DeviceForm(instance=device)
    context = {"form": form}
    return render(request, 'inventory/form.html', context)


@login_required(login_url='inventory:login')
def create_device(request):
    """This is the function for the create view for the :class:`~inventory.models.Device` model
    It uses the :class:`~inventory.forms.DeviceForm`

    .. note::
        Only for logged in Users

    :param request:
    :return:
    """
    if request.method == "POST":
        form = DeviceForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Changes successful!')
            return HttpResponseRedirect(reverse('inventory:dashboard'))
        else:
            messages.error(request, 'Error saving form')
    form = DeviceForm()
    context = {"form": form}
    return render(request, 'inventory/form.html', context)


@login_required(login_url='inventory:login')
def delete_device(request, pk):
    """This is the function for the delete view for the :class:`~inventory.models.Device` model

    .. note::
        Only for logged in Users

    :param pk:
    :param request:
    :return:
    """
    device = Device.objects.get(pk=pk)
    device.delete()
    return HttpResponseRedirect(reverse('inventory:dashboard'))


@login_required(login_url='inventory:login')
def product(request, pk):
    """This is the function for the detail view for the :class:`~inventory.models.Product` model

    .. note::
        Only for logged in Users

open_assetmanagement/inventory/templates/inventory/dashboard.html
{% extends 'inventory/main.html' %}

{% block content %}

{%  include 'inventory/status.html' %}

<div class="row p-3">
    <div class="col-md-6">
        <h5>Products</h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-info btn-sm btn-block" href="{% url 'inventory:create_product' %}">Create Product</a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Supplier</th>
                    <th>Model</th>
                    <th>Version</th>
                    <th>Type</th>
                    <th>EoS</th>
                    <th></th>
                </tr>

                {% for product in products %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'inventory:product' product.id %}">View</a></td>
                    <td>{{product.product_supplier_id}}</td>
                    <td>{{product.model}}</td>
                    <td>{{product.version}}</td>
                    <td>{{product.type}}</td>
                    <td>{{product.endOfSupport}}</td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'inventory:delete_product' product.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-md-6">
        <h5>Suppliers</h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-info btn-sm btn-block" href="{% url 'inventory:create_supplier' %}">Create Supplier</a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>name</th>
                    <th>Contact Info</th>
                    <th>Aquisition History</th>
                    <th>Support Contracts</th>
                    <th>Additional Info</th>
                    <th></th>
                </tr>

                {% for supplier in suppliers %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'inventory:supplier' supplier.id %}">View</a></td>
                    <td>{{supplier.name}}</td>
                    <td>{{supplier.contact_information}}</td>
                    <td>{{supplier.acquisitionHistory}}</td>
                    <td>{{supplier.supportContracts}}</td>
                    <td>{{supplier.additionalInformation}}</td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'inventory:delete_supplier' supplier.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<div class="row p-3">
    <div class="col-md-8">
        <h5>Devices</h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-info btn-sm btn-block" href="{% url 'inventory:create_device' %}">Create Device</a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Serial Number</th>
                    <th>MAC</th>
                    <th>IP</th>
                    <th>OS</th>
                    <th>Group</th>
                    <th>Network</th>
                    <th>Location</th>
                    <th></th>
                </tr>

                {% for device in devices %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'inventory:device' device.id %}">View</a></td>
                    <td>{{device.device_name}}</td>
                    <td>{{device.serial_number}}</td>
                    <td>{{device.mac_address}}</td>
                    <td>{{device.ip_address}}</td>
                    <td>{{device.os}}</td>
                    <td>{{device.group}}</td>
                    <td>{{device.network}}</td>
                    <td>{{device.location}}</td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'inventory:delete_device' device.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-md-4">
        <h5>Software</h5>
        <hr>
        <div class="card card-body">
            <a class="btn btn-info btn-sm btn-block" href="{% url 'inventory:create_software' %}">Create Software</a>
            <table class="table table-sm">
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Version</th>
                    <th>Ports</th>
                    <th>Category</th>
                    <th>EoS</th>
                    <th></th>
                </tr>
                {% for software in softwares %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'inventory:software' software.id %}">View</a></td>
                    <td>{{software.software_name}}</td>
                    <td>{{software.software_version}}</td>
                    <td>{{software.ports}}</td>
                    <td>{{software.software_category}}</td>
                    <td>{{software.software_endOfSupport}}</td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'inventory:delete_software' software.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock %}

open_assetmanagement/inventory/templates/inventory/device.html
{%  extends 'inventory/main.html' %}

{% block content %}

<br>

<div class="row p-3 pt-0">
    <div class="col-md">
        <div class="card card-body">
            <h5>Device: {{ device.device_name }}</h5>
            <hr>

            <p>Name: {{ device.device_name }}</p>
            <p>Serial Number: {{device.serial_number}}</p>
            <p>MAC: {{device.mac_address}}</p>
            <p>IP: {{device.ip_address}}</p>
            <p>OS: {{device.os}}</p>
            <p>Group: {{device.group}}</p>
            <p>Network: {{device.network}}</p>
            <p>Location: {{device.location}}</p>
            <div class="d-flex">
                <a class="btn flex-fill btn-outline-info  btn-sm btn-block me-1" href="{% url 'inventory:change_device' device.pk %}">Update Device</a>
                <a class="btn flex-fill btn-outline-danger  btn-sm btn-block" href="{% url 'inventory:delete_device' device.pk %}">Delete Device</a>
            </div>

        </div>
    </div>

    <div class="col-md-2">
        <div class="card card-body">
            <h5>Info</h5>
            <hr>

            {% if device.automatic_import %}
            <div class="alert alert-danger" role="alert">
                Warning! Automatic Import
            </div>
            {% endif %}
            {% if device.csv_import %}
            <div class="alert alert-warning" role="alert">
                Warning! CSV Import
            </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="row p-3 pt-0">
    <div class="col-md">
        <div class="card card-body">
            <h5>Product: {{ device.product_id.model }} {{ device.product_id.version }}</h5>
            <hr>

            <p>Model: {{ device.product_id.model }}</p>
            <p>Version: {{ device.product_id.version }}</p>
            <p>Type: {{ device.product_id.type }}</p>
            <p>EndOfSupport: {{ device.product_id.endOfSupport }}</p>

            {% if device.product_id %}
            <div class="d-flex">
                <a class="btn flex-fill btn-outline-info  btn-sm btn-block me-1" href="{% url 'inventory:product' device.product_id.pk %}">View Product</a>
                <a class="btn flex-fill btn-outline-info  btn-sm btn-block me-1" href="{% url 'inventory:change_product' device.product_id.pk %}">Update Product</a>
                <a class="btn flex-fill btn-outline-danger  btn-sm btn-block" href="{% url 'inventory:delete_product' device.product_id.pk %}">Delete Product</a>
            </div>
            {% else %}
                <a class="btn btn-outline-info btn-sm btn-block" href="{% url 'inventory:create_product' %}">Create Product</a>
            {% endif %}

        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Supplier: {{ device.product_id.product_supplier_id }}</h5>
            <hr>
            <p>Name: {{ device.product_id.product_supplier_id.name }}</p>
            <p>Contact Info: {{ device.product_id.product_supplier_id.contact_information }}</p>
            <p>Acquisition History: {{ device.product_id.product_supplier_id.acquisitionHistory }}</p>
            <p>Support Contracts: {{ device.product_id.product_supplier_id.supportContracts }}</p>
            <p>Additional Info: {{ device.product_id.product_supplier_id.additionalInformation }}</p>

            {% if device.product_id.product_supplier_id %}
            <div class="d-flex">
                <a class="btn flex-fill btn-outline-info  btn-sm btn-block me-1" href="{% url 'inventory:supplier' device.product_id.product_supplier_id.pk %}">View Supplier</a>
                <a class="btn flex-fill btn-outline-info  btn-sm btn-block me-1" href="{% url 'inventory:change_supplier' device.product_id.product_supplier_id.pk %}">Update Supplier</a>
                <a class="btn flex-fill btn-outline-danger  btn-sm btn-block" href="{% url 'inventory:delete_supplier' device.product_id.product_supplier_id.pk %}">Delete Supplier</a>
            </div>
            {% else %}
                <a class="btn btn-outline-info btn-sm btn-block" href="{% url 'inventory:create_supplier' %}">Create Supplier</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="row p-3 pt-0">
    <div class="card card-body">
        <h5>Installed Software</h5>
        <hr>
        <table class="table table-sm">
            <tr>
                <th></th>
                <th>Name</th>
            </tr>

            {% for software in softwares %}
            <tr>
                <td><a class="btn btn-sm btn-info" href="{% url 'inventory:software' software.id %}">View</a></td>
                <td>{{software.software_name}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
<br>

{% endblock %}

open_assetmanagement/inventory/templates/inventory/software.html
{%  extends 'inventory/main.html' %}

{% block content %}

<br>

<div class="row p-3 pt-0">
    <div class="col-md">
        <div class="card card-body">
            <h5>Software: {{ software.software_name }}</h5>
            <hr>
            <p>Name: {{ software.software_name }}</p>
            <p>Version: {{ software.software_version }}</p>
            <p>Contact: {{ software.contact_information }}</p>
            <p>Acquisition History: {{ software.acquisitionHistory  }}</p>
            <p>Support Contracts: {{ software.supportContracts  }}</p>
            <p>Additional Info: {{ software.additionalInformation }}</p>
            <div class="d-flex">
                <a class="btn flex-fill btn-outline-info  btn-sm btn-block me-1" href="{% url 'inventory:change_software' software.pk %}">Update software</a>
                <a class="btn flex-fill btn-outline-danger  btn-sm btn-block" href="{% url 'inventory:delete_software' software.pk %}">Delete software</a>
            </div>

        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Supplier: {{ software.product_supplier_id }}</h5>
            <hr>
            <p>Name: {{ software.product_supplier_id.name }}</p>
            <p>Contact Info: {{ software.product_supplier_id.contact_information }}</p>
            <p>Acquisition History: {{ software.product_supplier_id.acquisitionHistory }}</p>
            <p>Support Contracts: {{ software.product_supplier_id.supportContracts }}</p>
            <p>Additional Info: {{ software.product_supplier_id.additionalInformation }}</p>
            {% if software.product_supplier_id %}
                <div class="d-flex">
                    <a class="btn flex-fill btn-outline-info  btn-sm btn-block me-1" href="{% url 'inventory:supplier' software.product_supplier_id.pk %}">View Supplier</a>
                    <a class="btn flex-fill btn-outline-info  btn-sm btn-block me-1" href="{% url 'inventory:change_supplier' software.product_supplier_id.pk %}">Update Supplier</a>
                    <a class="btn flex-fill btn-outline-danger  btn-sm btn-block" href="{% url 'inventory:delete_supplier' software.product_supplier_id.pk %}">Delete Supplier</a>
                </div>
            {% else %}
                <a class="btn btn-outline-info btn-sm btn-block" href="{% url 'inventory:create_supplier' %}">Create Supplier</a>
            {% endif %}
        </div>
    </div>

    <div class="col-md-2">
        <div class="card card-body">
            <h5>Info</h5>
            <hr>
            <h1 style="text-align: center;padding: 10px"></h1>
        </div>
    </div>
</div>
<div class="row p-3 pt-0">
    <div class="card card-body">
        <h5>Devices with this Software</h5>
        <hr>
        <table class="table table-sm">
            <tr>
                <th></th>
                <th>Name</th>
                <th>Serial Number</th>
                <th>MAC</th>
                <th>IP</th>
                <th>OS</th>
                <th>Group</th>
                <th>Network</th>
                <th>Location</th>
            </tr>

            {% for device in devices %}
            <tr>
                <td><a class="btn btn-sm btn-info" href="{% url 'inventory:device' device.id %}">View</a></td>
                <td>{{device.device_name}}</td>
                <td>{{device.serial_number}}</td>
                <td>{{device.mac_address}}</td>
                <td>{{device.ip_address}}</td>
                <td>{{device.os}}</td>
                <td>{{device.group}}</td>
                <td>{{device.network}}</td>
                <td>{{device.location}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
<br>

{% endblock %}

open_assetmanagement/inventory/templates/inventory/supplier.html
{%  extends 'inventory/main.html' %}

{% block content %}

<br>

<div class="row p-3">
	<div class="col-md">
		<div class="card card-body">
			<h5>Supplier: {{ supplier }}</h5>
			<hr>
			<p>Name: {{ supplier.name }}</p>
			<p>Contact Info: {{ supplier.contact_information }}</p>
			<p>Acquisition History: {{ supplier.acquisitionHistory }}</p>
			<p>Support Contracts: {{ supplier.supportContracts }}</p>
			<p>Additional Info: {{ supplier.additionalInformation }}</p>
			<a class="btn btn-outline-info  btn-sm btn-block mb-2" href="{% url 'inventory:change_supplier' supplier.pk %}">Update Supplier</a>
			<a class="btn btn-outline-danger  btn-sm btn-block" href="{% url 'inventory:delete_supplier' supplier.pk %}">Delete Supplier</a>

		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Info</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px"></h1>
		</div>
	</div>
</div>

<br>

<div class="row p-3">
	{% if products %}
	<div class="col-md">
		<div class="card card-body">
			<h5>Products of this Supplier</h5>
			<hr>
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Model</th>
					<th>Version</th>
					<th>Type</th>
					<th>EoS</th>
				</tr>

				{% for product in products %}
				<tr>
					<td><a class="btn btn-sm btn-info" href="{% url 'inventory:product' product.id %}">View</a></td>
					<td>{{product.model}}</td>
					<td>{{product.version}}</td>
					<td>{{product.type}}</td>
					<td>{{product.endOfSupport}}</td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>
	{% endif %}
	{% if softwares %}
	<div class="col-md">
		<div class="card card-body">
			<h5>Software of this Supplier</h5>
			<hr>
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Model</th>
					<th>Version</th>
					<th>Type</th>
					<th>EoS</th>
				</tr>

				{% for software in softwares %}
				<tr>
					<td><a class="btn btn-sm btn-info" href="{% url 'inventory:software' software.id %}">View</a></td>
					<td>{{software.software_name}}</td>
					<td>{{software.software_version}}</td>
					<td>{{software.category}}</td>
					<td>{{software.endOfSupport}}</td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>
	{% endif %}
</div>

{% endblock %}